[platformio]
default_envs = native

[env:native]
platform = native
test_build_src = yes
build_src_filter =
    +<telemetry/>
    +<ecu/>
build_flags =
    -std=gnu++17

[env:waveshare_5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
framework = arduino
board = waveshare_esp32_s3_touch_lcd_5
monitor_speed = 115200
extra_scripts = post:scripts/merge_bin.py
lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
    https://github.com/lvgl/lvgl.git#v8.4.0
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=1
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_5
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DLV_COLOR_16_SWAP=0
    -I src
