#include "parameter_registry.h"

#include <array>

namespace {
constexpr std::array<ParameterDescriptor, parameterCount()> kDescriptors{{
    {ParameterId::Rpm, "Engine speed", "RPM", NativeUnit::Rpm, 0U},
    {ParameterId::Map, "Manifold pressure", "MAP", NativeUnit::Bar, 2U},
    {ParameterId::Lambda, "Lambda", "LAMBDA", NativeUnit::Lambda, 2U},
    {ParameterId::Tps, "Throttle position", "TPS", NativeUnit::Percent, 0U},
    {ParameterId::Clt, "Coolant temperature", "CLT", NativeUnit::Celsius, 0U},
    {ParameterId::Iat, "Intake air temperature", "IAT", NativeUnit::Celsius, 0U},
    {ParameterId::OilPressure, "Oil pressure", "OIL PRESS", NativeUnit::Bar, 1U},
    {ParameterId::OilTemperature, "Oil temperature", "OIL TEMP", NativeUnit::Celsius, 0U},
    {ParameterId::BatteryVoltage, "Battery voltage", "BATTERY", NativeUnit::Volt, 1U},
    {ParameterId::Speed, "Vehicle speed", "SPEED", NativeUnit::Kph, 0U},
    {ParameterId::Gear, "Gear", "GEAR", NativeUnit::Gear, 0U},
    {ParameterId::FuelPressure, "Fuel pressure", "FUEL PRESS", NativeUnit::Bar, 1U},
    {ParameterId::BarometricPressure, "Barometric pressure", "BARO", NativeUnit::Bar, 2U},
    {ParameterId::BoostTarget, "Boost target", "BOOST TARGET", NativeUnit::Bar, 2U},
    {ParameterId::CoolantPressure, "Coolant pressure", "CLT PRESS", NativeUnit::Bar, 1U},
    {ParameterId::FuelTemperature, "Fuel temperature", "FUEL TEMP", NativeUnit::Celsius, 0U},
    {ParameterId::EthanolContent, "Ethanol content", "ETHANOL", NativeUnit::Percent, 0U},
    {ParameterId::Lambda2, "Lambda 2", "LAMBDA 2", NativeUnit::Lambda, 2U},
    {ParameterId::IgnitionTiming, "Ignition timing", "IGN TIMING", NativeUnit::Degrees, 1U},
    {ParameterId::InjectorDuty, "Injector duty", "INJ DUTY", NativeUnit::Percent, 1U},
    {ParameterId::InjectorPulseWidth, "Injector pulse width", "INJ PW", NativeUnit::Milliseconds, 2U},
    {ParameterId::AcceleratorPosition, "Accelerator position", "ACCEL", NativeUnit::Percent, 1U},
    {ParameterId::MassAirFlow, "Mass air flow", "MAF", NativeUnit::GramsPerSecond, 1U},
    {ParameterId::Egt1, "Exhaust gas temperature 1", "EGT 1", NativeUnit::Celsius, 0U},
    {ParameterId::Egt2, "Exhaust gas temperature 2", "EGT 2", NativeUnit::Celsius, 0U},
    {ParameterId::Egt3, "Exhaust gas temperature 3", "EGT 3", NativeUnit::Celsius, 0U},
    {ParameterId::Egt4, "Exhaust gas temperature 4", "EGT 4", NativeUnit::Celsius, 0U},
    {ParameterId::Egt5, "Exhaust gas temperature 5", "EGT 5", NativeUnit::Celsius, 0U},
    {ParameterId::Egt6, "Exhaust gas temperature 6", "EGT 6", NativeUnit::Celsius, 0U},
    {ParameterId::Egt7, "Exhaust gas temperature 7", "EGT 7", NativeUnit::Celsius, 0U},
    {ParameterId::Egt8, "Exhaust gas temperature 8", "EGT 8", NativeUnit::Celsius, 0U},
    {ParameterId::WheelSpeedLf, "Wheel speed LF", "WHEEL LF", NativeUnit::Kph, 1U},
    {ParameterId::WheelSpeedLr, "Wheel speed LR", "WHEEL LR", NativeUnit::Kph, 1U},
    {ParameterId::WheelSpeedRf, "Wheel speed RF", "WHEEL RF", NativeUnit::Kph, 1U},
    {ParameterId::WheelSpeedRr, "Wheel speed RR", "WHEEL RR", NativeUnit::Kph, 1U},
    {ParameterId::IgnitionOn, "Ignition on", "IGNITION", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CrankSensorError, "Crank sensor error", "CRANK ERR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::MassAirFlowError, "Mass air flow error", "MAF ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::ClutchPressed, "Clutch pressed", "CLUTCH", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::IdleActive, "Idle active", "IDLE", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::EngineRunning, "Engine running", "RUNNING", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::BrakePressed, "Brake pressed", "BRAKE", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::BrakeSystemFault, "Brake system fault", "BRAKE FAULT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::KickdownActive, "Kickdown active", "KICKDOWN", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CheckEngine, "Check engine", "CHECK ENGINE", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::EmlWarning, "Electronic throttle warning", "EML", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::OilConsumptionWarning, "Oil consumption warning", "OIL USE", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::OilLossWarning, "Oil loss warning", "OIL LOSS", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::OilSensorFault, "Oil sensor fault", "OIL SENSOR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CoolantOverheat, "Coolant overheat", "OVERHEAT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::UpshiftRequest, "Upshift request", "UPSHIFT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::LowOilPressure, "Low oil pressure", "OIL PRESS LOW", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CoolantSensorError, "Coolant sensor error", "CLT ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::IntakeAirSensorError, "Intake air sensor error", "IAT ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::MapSensorError, "MAP sensor error", "MAP ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::WidebandSensorError, "Wideband sensor error", "WBO ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::Egt1SensorError, "EGT 1 sensor error", "EGT 1 ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::Egt2SensorError, "EGT 2 sensor error", "EGT 2 ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::EgtHighAlarm, "EGT high alarm", "EGT HIGH", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::KnockDetected, "Knock detected", "KNOCK", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::FlexFuelSensorError, "Flex fuel sensor error", "FLEX ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::DbwError, "Drive by wire error", "DBW ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::FuelPressureError, "Fuel pressure error", "FUEL P ERROR", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::GearCutActive, "Gear cut active", "GEAR CUT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::AntiLagActive, "Anti-lag active", "ANTI-LAG", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::LaunchControlActive, "Launch control active", "LAUNCH", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::TractionControlActive, "Traction control active", "TRACTION", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::PitLimiterActive, "Pit limiter active", "PIT LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::FuelPumpActive, "Fuel pump active", "FUEL PUMP", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CoolantFanActive, "Coolant fan active", "FAN 1", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::AcClutchActive, "AC clutch active", "AC CLUTCH", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::AcFanActive, "AC fan active", "AC FAN", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::NitrousActive, "Nitrous active", "NITROUS", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::StarterRequestActive, "Starter request active", "STARTER", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::RevLimiterActive, "Rev limiter active", "REV LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::MainRelayActive, "Main relay active", "MAIN RELAY", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::O2HeaterActive, "O2 heater active", "O2 HEATER", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::LambdaProtectionActive, "Lambda protection active", "LAMBDA PROT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CoolantFan2Active, "Coolant fan 2 active", "FAN 2", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::ShiftCutActive, "Shift cut active", "SHIFT CUT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::TractionPowerLimiterActive, "Traction power limiter active", "TC POWER", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::ThrottleBlipActive, "Throttle blip active", "BLIP", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::AcIdleUpActive, "AC idle up active", "AC IDLE UP", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::SpeedLimiterActive, "Speed limiter active", "SPEED LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::GpLimiterActive, "GP limiter active", "GP LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::UserCutActive, "User cut active", "USER CUT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::EcuLoggingActive, "ECU logging active", "LOGGING", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::MapLimiterActive, "MAP limiter active", "MAP LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::MaxIgnitionLimiterActive, "Maximum ignition limiter active", "IGN LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::AntiLagIgnitionCutActive, "Anti-lag ignition cut active", "ALS IGN CUT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::HighVoltageLimitActive, "High voltage limit active", "VOLT HIGH", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::OverrunActive, "Overrun active", "OVERRUN", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::LowVoltageLimitActive, "Low voltage limit active", "VOLT LOW", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::LaunchRpmLimitActive, "Launch RPM limit active", "LAUNCH LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::WakeupActive, "Wakeup active", "WAKEUP", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::GpRpmLimit1Active, "GP RPM limit 1 active", "GP RPM 1", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::ClosedLoopStepperLimitActive, "Closed loop stepper limit active", "CL STEPPER", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::GpRpmLimit2Active, "GP RPM limit 2 active", "GP RPM 2", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::EThrottleLimitActive, "Electronic throttle limit active", "ETB LIMIT", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CyclicIdleActive, "Cyclic idle active", "CYCLIC IDLE", NativeUnit::None, 0U, ParameterKind::Flag},
    {ParameterId::CruiseControlActive, "Cruise control active", "CRUISE", NativeUnit::None, 0U, ParameterKind::Flag},
}};

constexpr ParameterDescriptor kUnknown{
    ParameterId::Count, "Unknown", "---", NativeUnit::None, 0U};
}  // namespace

const ParameterDescriptor& parameterDescriptor(ParameterId id) {
    const std::size_t index = static_cast<std::size_t>(id);
    return index < kDescriptors.size() ? kDescriptors[index] : kUnknown;
}
