#pragma once

#include <cstdint>

enum class ParameterId : uint16_t {
    Rpm = 0,
    Tps = 1,
    Map = 2,
    BoostTarget = 3,
    InjectorPulseWidth = 4,
    IgnitionAngle = 5,
    Dwell = 6,
    Iat = 7,
    Clt = 8,
    OilTemperature = 9,
    EcuTemperature = 10,
    Egt1 = 11,
    Egt2 = 12,
    BarometricPressure = 13,
    OilPressure = 14,
    FuelPressure = 15,
    Lambda = 16,
    LambdaTarget = 17,
    LambdaCorrection = 18,
    EthanolContent = 19,
    FuelUsed = 20,
    VehicleSpeed = 21,
    Gear = 22,
    DbwPosition = 23,
    DbwTarget = 24,
    BatteryVoltage = 25,
    Ain1 = 26,
    Ain2 = 27,
    Ain3 = 28,
    Ain4 = 29,
    Ain5 = 30,
    Ain6 = 31,
    Pwm1 = 32,
    Pwm2 = 33,
    TcDifferentialRpmRaw = 34,
    TcDifferentialRpmFiltered = 35,
    TcTorqueReduction = 36,
    PitLimiterTorqueReduction = 37,
    EcuError = 38,
    ErrorFlagRaw = EcuError,
    LaunchControlActive = 39,
    AntiLagActive = 40,
    GearCutActive = 41,
    TractionControlActive = 42,
    PitLimiterActive = 43,
    BrakeActive = 44,
    FuelPumpActive = 45,
    FanActive = 46,
    NitrousActive = 47,
    CanSwitch1 = 48,
    CanSwitch2 = 49,
    CanSwitch3 = 50,
    CanSwitch4 = 51,

    CltSensorError = 52,
    IatSensorError = 53,
    MapSensorError = 54,
    WidebandError = 55,
    Egt1SensorError = 56,
    Egt2SensorError = 57,
    EgtAlarm = 58,
    Knocking = 59,
    FlexFuelSensorError = 60,
    DbwError = 61,
    FuelPressureRelativeError = 62,
    IdleActive = 63,
    TableSet2Active = 64,
    ParametricOutput1 = 65,
    ParametricOutput2 = 66,
    ParametricOutput3 = 67,
    ParametricOutput4 = 68,
    ParametricOutput5 = 69,
    VirtualOutput1 = 70,
    VirtualOutput2 = 71,
    VirtualOutput3 = 72,
    CanSwitch5 = 73,
    CanSwitch6 = 74,
    CanSwitch7 = 75,
    CanSwitch8 = 76,
    Switch1 = 77,
    Switch2 = 78,
    Switch3 = 79,
    MuxSwitch1 = 80,
    MuxSwitch2 = 81,
    MuxSwitch3 = 82,
    LaunchMapSet = 83,
    AlsMapSet = 84,
    AcClutchActive = 85,
    AcFanActive = 86,
    StarterRequest = 87,
    BoostMapSet = 88,
    DsgMode = 89,
    Count = 90
};

constexpr uint16_t parameterIndex(ParameterId id) {
    return static_cast<uint16_t>(id);
}
