#pragma once

#include <cstddef>
#include <cstdint>

enum class ParameterId : uint8_t {
    Rpm,
    Map,
    Lambda,
    Tps,
    Clt,
    Iat,
    OilPressure,
    OilTemperature,
    BatteryVoltage,
    Speed,
    Gear,
    FuelPressure,
    BarometricPressure,
    BoostTarget,
    CoolantPressure,
    FuelTemperature,
    EthanolContent,
    Lambda2,
    IgnitionTiming,
    InjectorDuty,
    InjectorPulseWidth,
    AcceleratorPosition,
    MassAirFlow,
    Egt1,
    Egt2,
    Egt3,
    Egt4,
    Egt5,
    Egt6,
    Egt7,
    Egt8,
    WheelSpeedLf,
    WheelSpeedLr,
    WheelSpeedRf,
    WheelSpeedRr,
    IgnitionOn,
    CrankSensorError,
    MassAirFlowError,
    ClutchPressed,
    IdleActive,
    EngineRunning,
    BrakePressed,
    BrakeSystemFault,
    KickdownActive,
    CheckEngine,
    EmlWarning,
    OilConsumptionWarning,
    OilLossWarning,
    OilSensorFault,
    CoolantOverheat,
    UpshiftRequest,
    LowOilPressure,
    CoolantSensorError,
    IntakeAirSensorError,
    MapSensorError,
    WidebandSensorError,
    Egt1SensorError,
    Egt2SensorError,
    EgtHighAlarm,
    KnockDetected,
    FlexFuelSensorError,
    DbwError,
    FuelPressureError,
    GearCutActive,
    AntiLagActive,
    LaunchControlActive,
    TractionControlActive,
    PitLimiterActive,
    FuelPumpActive,
    CoolantFanActive,
    AcClutchActive,
    AcFanActive,
    NitrousActive,
    StarterRequestActive,
    RevLimiterActive,
    MainRelayActive,
    O2HeaterActive,
    LambdaProtectionActive,
    CoolantFan2Active,
    ShiftCutActive,
    TractionPowerLimiterActive,
    ThrottleBlipActive,
    AcIdleUpActive,
    SpeedLimiterActive,
    GpLimiterActive,
    UserCutActive,
    EcuLoggingActive,
    MapLimiterActive,
    MaxIgnitionLimiterActive,
    AntiLagIgnitionCutActive,
    HighVoltageLimitActive,
    OverrunActive,
    LowVoltageLimitActive,
    LaunchRpmLimitActive,
    WakeupActive,
    GpRpmLimit1Active,
    ClosedLoopStepperLimitActive,
    GpRpmLimit2Active,
    EThrottleLimitActive,
    CyclicIdleActive,
    CruiseControlActive,
    Count,
};

using VehicleSignal = ParameterId;

constexpr std::size_t parameterCount() {
    return static_cast<std::size_t>(ParameterId::Count);
}

enum class NativeUnit : uint8_t {
    None,
    Rpm,
    Bar,
    Lambda,
    Percent,
    Celsius,
    Volt,
    Kph,
    Gear,
    Degrees,
    Milliseconds,
    GramsPerSecond,
};
